# Multi-Agent Automation Service MCP Configuration
# mcp_agent.config.yaml

# MCP 서버 설정
mcp:
  servers:
    filesystem:
      command: "npx"
      args: ["@modelcontextprotocol/server-filesystem"]
      description: "파일 시스템 접근을 위한 MCP 서버"
    
    playwright:
      command: "npx"
      args: ["@playwright/mcp@latest"]
      description: "웹 브라우저 자동화를 위한 MCP 서버"
    
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch"]
      description: "웹 콘텐츠 가져오기를 위한 MCP 서버"
    
    github:
      command: "npx"
      args: ["@modelcontextprotocol/server-github"]
      description: "GitHub 접근을 위한 MCP 서버"

# LLM 설정
llm:
  provider: "gemini"
  model: "gemini-2.5-flash-lite-preview-06-07"
  temperature: 0.1
  max_tokens: 4000

# 로깅 설정
logging:
  level: "INFO"
  format: "json"
  output: "logs/multi_agent_automation.log"

# 실행 설정
execution:
  max_steps: 50
  timeout: 300  # 5분
  retry_attempts: 3

# Gemini CLI 설정
gemini:
  enabled: true
  timeout: 300
  max_retries: 3

# 스케줄링 설정
scheduling:
  enabled: true
  timezone: "Asia/Seoul"
  jobs:
    daily_automation:
      schedule: "0 2 * * *"  # 매일 새벽 2시
      type: "full_automation"
    
    code_review:
      schedule: "0 9 * * 1"  # 매주 월요일 오전 9시
      type: "code_review"
    
    deployment_check:
      schedule: "0 * * * *"  # 매시간
      type: "deployment_check" 