# SEO Doctor MCP Agent Configuration
# Based on real-world MCP implementations from:
# https://medium.com/@matteo28/how-i-solved-a-real-world-customer-problem-with-the-model-context-protocol-mcp-328da5ac76fe

# MCP Server Configuration for SEO Analysis
mcp:
  servers:
    # Google Search MCP Server
    g-search:
      command: "npx"
      args: ["-y", "g-search-mcp"]
      env:
        GOOGLE_SEARCH_API_KEY: "${GOOGLE_SEARCH_API_KEY}"
        GOOGLE_SEARCH_ENGINE_ID: "${GOOGLE_SEARCH_ENGINE_ID}"
      
    # Fetch MCP Server for website analysis
    fetch:
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-fetch"]
      
    # Lighthouse MCP Server for performance analysis
    lighthouse:
      command: "npx"
      args: ["-y", "lighthouse-mcp-server"]
      
    # Filesystem MCP Server for report generation
    filesystem:
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-filesystem"]
      # Security: Only allow access to specific directories
      env:
        ALLOWED_PATHS: "seo_doctor_reports/,reports/"
        
    # Gmail MCP Server for sending SEO reports (optional)
    gmail:
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-gmail"]
      env:
        GMAIL_CLIENT_ID: "${GMAIL_CLIENT_ID}"
        GMAIL_CLIENT_SECRET: "${GMAIL_CLIENT_SECRET}"
        
    # Google Sheets MCP Server for data export (optional)
    google-sheets:
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-google-sheets"]
      env:
        GOOGLE_SHEETS_CLIENT_ID: "${GOOGLE_SHEETS_CLIENT_ID}"
        GOOGLE_SHEETS_CLIENT_SECRET: "${GOOGLE_SHEETS_CLIENT_SECRET}"

# Security Configuration
security:
  # Read-only access for most servers
  default_permissions: "read"
  
  # Specific permissions per server
  server_permissions:
    filesystem:
      - "read"
      - "write"  # Only for report generation
    gmail:
      - "send"   # Only for sending reports
    google-sheets:
      - "read"
      - "write"  # For data export
      
# SEO Analysis Configuration
seo_analysis:
  # Default analysis parameters
  lighthouse:
    mobile_emulation: true
    categories: ["performance", "seo", "accessibility", "best-practices"]
    throttling: "mobile3G"
    
  search:
    max_results: 10
    safe_search: "active"
    
  reporting:
    auto_save: true
    format: "markdown"
    include_raw_data: true
    
# Rate Limiting (to avoid API abuse) 
rate_limits:
  lighthouse: 
    requests_per_minute: 10
  g-search:
    requests_per_minute: 100
  fetch:
    requests_per_minute: 60
    
# Logging Configuration
logging:
  level: "INFO"
  include_mcp_requests: true
  include_responses: false  # For security
  
# Output Configuration
output:
  reports_directory: "seo_doctor_reports"
  max_file_size: "10MB"
  retention_days: 30 